version: '3.3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - main-net
  web:
    build: web
    restart: always
    ports:
      - 8000:8000
    networks:
      - main-net

networks:
  main-net:
    driver: bridge

volumes:
  db:
    driver: local